### ISSUE TITLE
Table headers separator line unexpectedly changes on table format 

### ISSUE THREAD

**Issue by lechu445** [shuGH/vscode-table-formatter#6]
Format table changes line separator that separates headers from data. Formating table puts a one space padding in each cell of this line. 
This issue illustrates an example.
For example we've got this table:
```
| header_1 | header_2 |
|----------|----------|
| val1 | val2 |
```
After "Format all" we've got
```
| header_1 | header_2 |
| -------- | -------- |
| val1     | val2     |
```
As we can see, in second line the table formatter replaced some "-" signs with spaces. It was unnecessary and bad because we change table definition format.
Please, fix this because it is a common scenario - headers and separators line from this example can be created and handled with plugin TableEditor to Sublime.

**Comment by unnamedcrewman** [comment]
I would be interested in this also.  I use [Pandoc](http://pandoc.org/index.html) a lot, and the table parser in Pandoc seems to choke when the heading separator line has whitespace between the pipe character and a colon, as in the following example.

    | header_1 | header_2 |
    | :------- | :------: |
    | val1     |   val2   |

Pandoc will parse this example just fine:

    | header_1 | header_2 |
    |:---------|:--------:|
    | val1     |   val2   |

Basically, for Pandoc it seems best not to have any whitespace in the heading separator line. The whitespace in all the other cells is fine.

Would it be possible simply to remove all whitespace from the separator line in the formatting process?

If this change is something  you would prefer not to implement, could you show me the place in the code where that whitespace is added?  I've looked through it, but my javascript skills are not quite good enough for me to determine how every thing fits together.

Thanks for your time.  The extension is really well done.

**Comment by shuGH** [comment]
Thank you for bug report and bug fix and using this extension.
I will check and merge and release it next week.
Wait a moment.

**Comment by shuGH** [comment]
i'm planning to add config.

title : markdown header hyphen type
1. with space : `| ----- |`
2. no space : `|-----|`
3. minimum : `|  ---  |`
4. auto fill : chose 1 or 2 automaticaly

cf. https://help.github.com/articles/organizing-information-with-tables/

**Comment by shuGH** [comment]
updated!
try set "tableformatter.markdown.oneSpacePadding: false"
