### ISSUE TITLE
Border-less Markdown tables

### ISSUE THREAD

**Issue by LeviticusMB** [shuGH/vscode-table-formatter#7]
I love how easy it is to reformat the current table, or all, in a Markdown file, but I'm not too found of the styling. I much prefer borderless tables.

Any chance you could add that?

There is another table formatter, https://marketplace.visualstudio.com/items?itemName=darkriszty.markdown-table-prettify, which detects the table style automatically. Would be really nice if you could do that too!

**Comment by shuGH** [comment]
Thanks for using.
And sorry for my late reply.
I understood the request.

I was unexpected it, but good function!
I will consider it.
Perhaps, in May as adding config.

**Comment by shuGH** [comment]
Thank you for waiting.
I released v1.2.1 and added borderless table configration.
Try `tableformatter.markdown.tableEdgesType = "Borderless"`.

**Comment by LeviticusMB** [comment]
Awesome! I like it!

Thanks.
