### ISSUE TITLE
'℃'の文字を含む場合の動作について

### ISSUE THREAD

**Issue by sanofk** [shuGH/vscode-table-formatter#9]
'℃'の文字を含む場合、以下のようにずれてしまいます。

    | column0 | column1 |
    | ------- | ------- |
    | ℃        |         |

**Comment by shuGH** [comment]
報告ありがとうございます
対応したいと思います

## 原因

文字数のカウンティングは、内部的に以下のライブラリを使用しています
[string-width](https://www.npmjs.com/package/string-width)
これはjsのlengthは、全角文字でも1を返すためです
このライブラリは全角文字に対し長さ2を返すのですが、今回のように特定の文字に対しては1になってしまいます

## 対応

#6 や #7 の対応でConfigを用意するのを考えています
上記の対応に合わせ、例外として2文字として判定する文字を指定出来るような項目を追加予定です

**Comment by shuGH** [comment]
1.1.2 をリリースしました
下記のような設定をしてみて下さい
"tableformatter.common.explicitFullwidthChars": ["℃"]

**Comment by sanofk** [comment]
正常に動作すること確認しました。
(確認環境 : Windows7 32bit. VSCode 1.12.2)
素早い対応ありがどうございます。
